// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDmpYTxv76x_STgDfrQPyPPXmGqq_v1M0M',
      appId: '1:12882114036:android:c02dd958eca965f5',
      messagingSenderId: '12882114036',
      projectId: 'galssapp-205313',
      databaseURL: 'https://galssapp-205313.firebaseio.com',
      storageBucket: 'galssapp-205313.appspot.com');

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyCTEP1Gm5D_5fqaW2uEmx7b63JP7V3yt5U',
      appId: '1:12882114036:ios:914e75cca8b4cbc548f5a1',
      messagingSenderId: '12882114036',
      projectId: 'galssapp-205313',
      databaseURL: 'https://galssapp-205313.firebaseio.com',
      storageBucket: 'galssapp-205313.appspot.com',
      iosClientId:
          '12882114036-k57q35adku9ft1j4ccfco51a164bd311.apps.googleusercontent.com',
      iosBundleId: 'com.iscodeablesolutions.apps.galss');
}
